apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-mywp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywp
  template:
    metadata:
      labels:
        app: mywp
    spec:
      containers:
      - name: pod-mywp
        image: 211.183.3.10:5000/jenwp:1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mywp
spec:
  type: NodePort
  selector:
    app: mywp
  ports:
  - nodePort: 30400
    port: 80
    targetPort: 80

