apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: pod-mydb
        image: 211.183.3.10:5000/jendb:1
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mydb
spec:
  type: NodePort
  selector:
    app: mydb
  ports:
  - nodePort: 31400
    port: 3306
    targetPort: 3306

